### ISSUE TITLE
Requires zlib version >=1.2.9 

### ISSUE THREAD

**Issue by jeffwang0516** [wetzel-desy/mod_want_digest#4]
![image](https://user-images.githubusercontent.com/11273319/115509711-57bf5480-a2b1-11eb-8743-2ddc5225fcb8.png)

- adler32_z is added after version 1.2.9
- Ref https://github.com/madler/zlib/blob/cacf7f1d4e3d44d871b605da3b647f07d718623f/ChangeLog

**Comment by wetzel-desy** [comment]
Hi Jeff, 
thank you for pointing that out. I will add the requirement to the Readme. 

Cheers,
Tim
